const Productos = [
    {
      productId: 1000,
      productName: "delightful chocolate Ilise",
      productImage: "https://picsum.photos/400?image=659",
      productStock: 81,
      productPrice: "23488.67",
      productSalePrice: "23488.67",
      category: "adultos",
    },
    {
      productId: 1001,
      productName: "civilian salmon Delinda",
      productImage: "https://picsum.photos/400?image=261",
      productStock: 66,
      productPrice: "42992.62",
      productSalePrice: "20636.46",
      category: "adultos",
    },
    {
      productId: 1002,
      productName: "northern chocolate Dagmar",
      productImage: "https://picsum.photos/400?image=921",
      productStock: 58,
      productPrice: "26956.67",
      productSalePrice: "26956.67",
      category: "adultos",
    },
    {
      productId: 1004,
      productName: "arrogant tan Nelia",
      productImage: "https://picsum.photos/400?image=924",
      productStock: 85,
      productPrice: "27379.36",
      productSalePrice: "9308.98",
      category: "adultos",
    },
    {
      productId: 1005,
      productName: "following bronze Misti",
      productImage: "https://picsum.photos/400?image=340",
      productStock: 24,
      productPrice: "34617.96",
      productSalePrice: "34617.96",
      category: "adultos",
    },
   {
     productId: 1007,
     productName: "sufficient peach Georgiana",
     productImage: "https://picsum.photos/400?image=860",
     productStock: 55,
     productPrice: "15506.06",
     productSalePrice: "15506.06",
     category: "adultos",
   },
   {
     productId: 1008,
     productName: "frequent sapphire Petronella",
     productImage: "https://picsum.photos/400?image=913",
     productStock: 36,
     productPrice: "44132.59",
     productSalePrice: "44132.59",
     category: "adultos",
   },
   {
     productId: 1009,
     productName: "indirect indigo Fiona",
     productImage: "https://picsum.photos/400?image=583",
     productStock: 49,
     productPrice: "40702.21",
     productSalePrice: "4477.24",
     category: "adultos",
   },
   {
     productId: 1010,
     productName: "gross plum Veriee",
     productImage: "https://picsum.photos/400?image=306",
     productStock: 12,
     productPrice: "42194.21",
     productSalePrice: "42194.21",
     category: "adultos",
   },
   {
     productId: 1011,
     productName: "gigantic red Lissy",
     productImage: "https://picsum.photos/400?image=184",
     productStock: 45,
     productPrice: "18745.19",
     productSalePrice: "8810.24",
     category: "adultos",
   },
   {
     productId: 1012,
     productName: "blind copper Dionne",
     productImage: "https://picsum.photos/400?image=308",
     productStock: 27,
     productPrice: "2038.28",
     productSalePrice: "448.42",
     category: "chicos",
   },
   {
     productId: 1013,
     productName: "varied indigo Lizzie",
     productImage: "https://picsum.photos/400?image=453",
     productStock: 97,
     productPrice: "28245.22",
     productSalePrice: "9603.37",
     category: "chicos",
   },
   {
     productId: 1014,
     productName: "single amaranth Doris",
     productImage: "https://picsum.photos/400?image=325",
     productStock: 21,
     productPrice: "4200.08",
     productSalePrice: "4200.08",
     category: "chicos",
   },
   {
     productId: 1015,
     productName: "keen maroon Lenette",
     productImage: "https://picsum.photos/400?image=92",
     productStock: 88,
     productPrice: "2282.88",
     productSalePrice: "2282.88",
     category: "chicos",
   },
   {
     productId: 1016,
     productName: "conservation peach Nari",
     productImage: "https://picsum.photos/400?image=798",
     productStock: 31,
     productPrice: "45707.28",
     productSalePrice: "45707.28",
     category: "chicos",
   },
   {
     productId: 1017,
     productName: "loyal blush Happy",
     productImage: "https://picsum.photos/400?image=163",
     productStock: 58,
     productPrice: "40390.62",
     productSalePrice: "16560.15",
     category: "chicos",
   },
   {
     productId: 1018,
     productName: "awkward jade Wini",
     productImage: "https://picsum.photos/400?image=475",
     productStock: 46,
     productPrice: "4221.73",
     productSalePrice: "4221.73",
     category: "Chicos",
   },
   {
     productId: 1019,
     productName: "uncertain cyan Tawsha",
     productImage: "https://picsum.photos/400?image=18",
     productStock: 24,
     productPrice: "6790.39",
     productSalePrice: "6790.39",
     category: "chicos",
   },
   {
     productId: 1020,
     productName: "partial harlequin Katlin",
     productImage: "https://picsum.photos/400?image=466",
     productStock: 15,
     productPrice: "9001.19",
     productSalePrice: "3510.47",
     category: "chicos",
   },
   {
     productId: 1021,
     productName: "redundant emerald Allyson",
     productImage: "https://picsum.photos/400?image=110",
     productStock: 59,
     productPrice: "25272.78",
     productSalePrice: "3032.73",
     category: "chicos",
   }
]
  
  export const db = new Promise((respuesta, rechazo) => {
    let resp = "200";
    if (resp === "200") {
      setTimeout(() => {
        respuesta(Productos);
      }, 2000);
    } else {
      rechazo("Error 404");
    }
  });

